# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Quantic Games"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Creating games with stories that are worth remembering."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:  ""

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://quanticgames.com/"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "Quantic Games"

# Social links in the site footer
twitter_username: "quanticgamesbo"
facebook_username: "quanticgames"
instagram_username: "quanticgamesbo"
linkedin_username: ""

collections:
  projects:
    output: true
    permalink: /projects/:name